services:
  api:
    image: oven/bun:latest
    container_name: bunjs
    ports:
      - "80:80"
    command: ["bun", "run", "--hot", "index.ts"]
    volumes:
      - ./hybrid:/home/bun/app
    depends_on:
      - database
      
  database:
    image: mysql:latest
    user: "mysql:mysql"
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: agrofamlink
      MYSQL_USER: userteste
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: mysql_data
        target: /var/lib/mysql

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
    name: app-network
