services:
  api:
    image: oven/bun:latest
    container_name: bunjs
    ports:
      - "80:80"
    command: ["bun", "run", "--hot", "index.ts"]
    volumes:
      - ./hybrid:/home/bun/app
    depends_on:
      - db
    networks:
      app-network:
        aliases:
          - api.local
      
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: teste
      MYSQL_USER: userteste
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app-network:
        aliases:
          - db.local

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
    name: app-network